// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7rNaO8Fs1AydYxfCok_vR5zzW5e2LYg',
    appId: '1:496986444678:web:38ba1e3f4ae076b0b19207',
    messagingSenderId: '496986444678',
    projectId: 'xploverse-flutter-283df',
    authDomain: 'xploverse-flutter-283df.firebaseapp.com',
    storageBucket: 'xploverse-flutter-283df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgzKit55Ok8QdOLP2zoz5f9rlXtaR_jw',
    appId: '1:496986444678:android:aff35528497545e5b19207',
    messagingSenderId: '496986444678',
    projectId: 'xploverse-flutter-283df',
    storageBucket: 'xploverse-flutter-283df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw-oKQrKAUU_N78_QQzM5Y7ZSyeYp2ho8',
    appId: '1:496986444678:ios:fda602714b8bdbe4b19207',
    messagingSenderId: '496986444678',
    projectId: 'xploverse-flutter-283df',
    storageBucket: 'xploverse-flutter-283df.appspot.com',
    iosBundleId: 'com.example.flutterXploverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw-oKQrKAUU_N78_QQzM5Y7ZSyeYp2ho8',
    appId: '1:496986444678:ios:fda602714b8bdbe4b19207',
    messagingSenderId: '496986444678',
    projectId: 'xploverse-flutter-283df',
    storageBucket: 'xploverse-flutter-283df.appspot.com',
    iosBundleId: 'com.example.flutterXploverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw7rNaO8Fs1AydYxfCok_vR5zzW5e2LYg',
    appId: '1:496986444678:web:11a663d821d412f4b19207',
    messagingSenderId: '496986444678',
    projectId: 'xploverse-flutter-283df',
    authDomain: 'xploverse-flutter-283df.firebaseapp.com',
    storageBucket: 'xploverse-flutter-283df.appspot.com',
  );
}
